export const SUBSCRIPTION_LIST_MY_REQUEST = 'SUBSCRIPTION_LIST_MY_REQUEST';
export const SUBSCRIPTION_LIST_MY_SUCCESS = 'SUBSCRIPTION_LIST_MY_SUCCESS';
export const SUBSCRIPTION_LIST_MY_FAIL = 'SUBSCRIPTION_LIST_MY_FAIL';
export const SUBSCRIPTION_LIST_MY_RESET = 'ORDER_LIST_MY_RESET';

export const SUBSCRIPTION_CANCEL_REQUEST = 'SUBSCRIPTION_CANCEL_REQUEST';
export const SUBSCRIPTION_CANCEL_SUCCESS = 'SUBSCRIPTION_CANCEL_SUCCESS';
export const SUBSCRIPTION_CANCEL_FAIL = 'SUBSCRIPTION_CANCEL_FAIL';
